apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "contacts.fullname" . }}
  labels:
    {{- include "contacts.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
